eight_points_guzzle:
    clients:
        api_aladhan:
            base_url: http://api.aladhan.com/v1/
            options:
                timeout: 30
                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    User-Agent: MobiblancMamda/7.0
                    Accept: application/json
            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~
        api_weather_yahoo:
            base_url: http://query.yahooapis.com/v1/public/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
                    Accept: application/json
            plugin: ~
        api_locator_yahoo:
            base_url: https://www.yahoo.com/news/_td/api/resource/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
                    Accept: application/json
            plugin: ~
        api_pharmacie:
            base_url: http://pharma.mobiblanc.com/json.php/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
            plugin: ~
        api_sms:
            base_url: http://smsprod.mobiblanc.com/api.php/send_sms/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
            plugin: ~
        api_devis_auto:
            base_url: http://demo3896531.mockable.io/auto
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
            plugin: ~
        api_devis_auto_mesure:
            base_url: http://demo3896531.mockable.io/auto/
            options:
                 timeout: 30
                 headers:
                    User-Agent: MobiblancMamda/7.0
                    plugin: ~
        api_devis_habitation:
                    base_url: http://demo3896531.mockable.io/
                    options:
                         timeout: 30
                         headers:
                            User-Agent: MobiblancMamda/7.0
                            plugin: ~