eight_points_guzzle:
    clients:
        api_aladhan:
            base_url: http://api.aladhan.com/v1/
            options:
                timeout: 30
                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    User-Agent: MobiblancMamda/7.0
                    Accept: application/json
            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~
        api_weather_yahoo:
            base_url: http://query.yahooapis.com/v1/public/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
                    Accept: application/json
            plugin: ~
        api_locator_yahoo:
            base_url: https://www.yahoo.com/news/_td/api/resource/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
                    Accept: application/json
            plugin: ~
        api_pharmacie:
            base_url: http://pharma.mobiblanc.com/json.php/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
            plugin: ~
        api_sms:
            base_url: http://smsprod.mobiblanc.com/api.php/send_sms/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
            plugin: ~
        api_devis_auto:
            base_url: https://ais.mamda-mcma.ma/WS/api/auto/post/
            options:
                timeout: 30
                headers:
                    User-Agent: MobiblancMamda/7.0
            plugin: ~
        api_devis_auto_mesure:
            base_url: https://ais.mamda-mcma.ma/WS/api/auto/mesure/post/
            options:
                 timeout: 30
                 headers:
                    User-Agent: MobiblancMamda/7.0
                    plugin: ~
        api_devis_habitation:
                    base_url: https://ais.mamda-mcma.ma/WS/api/rd/post
                    options:
                         timeout: 30
                         headers:
                            User-Agent: MobiblancMamda/7.0
                            plugin: ~
        api_add_contrat:
                    base_url: https://ais.mamda-mcma.ma/WS/api/contrat/add/post/
                    options:
                        timeout: 30
                        headers:
                            User-Agent: MobiblancMamda/7.0
                    plugin: ~
        api_details_contrat:
                    base_url: https://ais.mamda-mcma.ma/WS/api/contrat/det/post/
                    options:
                        timeout: 30
                        headers:
                            User-Agent: MobiblancMamda/7.0
                    plugin: ~
        preDeclarationTrigger:
                    base_url: https://ais.mamda-mcma.ma/WS/api/predeclaration/reponse/post
                    options:
                        timeout: 30
                        headers:
                            User-Agent: MobiblancMamda/7.0
                    plugin: ~
        api_get_cities:
                    base_url: http://demo0230142.mockable.io/listVilles
                    options:
                        timeout: 30
                        headers:
                            User-Agent: MobiblancMamda/7.0
                    plugin: ~
        api_get_garages:
                    base_url: http://demo0230142.mockable.io/listGarages
                    options:
                        timeout: 30
                        headers:
                            User-Agent: MobiblancMamda/7.0
                    plugin: ~
        api_send_MDR:
                    base_url: http://demo0949329.mockable.io/send
                    options:
                        timeout: 30
                        headers:
                            User-Agent: MobiblancMamda/7.0
                    plugin: ~
        api_get_doc:
                    base_url: http://demo0949329.mockable.io/download
                    options:
                        timeout: 30
                        headers:
                            User-Agent: MobiblancMamda/7.0
                    plugin: ~
        api_upload_doc:
                    base_url: http://demo3201186.mockable.io/uploadDoc
                    options:
                        timeout: 30
                        headers:
                            User-Agent: MobiblancMamda/7.0
                    plugin: ~