eight_points_guzzle:
    clients:
        api_aladhan:
            base_url: http://api.aladhan.com/v1/
            options:
                timeout: 30
                # Configure headers.
                # More info: http://docs.guzzlephp.org/en/stable/request-options.html#headers
                headers:
                    User-Agent: MobiblancMamda/7.0
                    Accept: application/json
            # Find plugins here:
            # https://github.com/8p/EightPointsGuzzleBundle#known-and-supported-plugins
            plugin: ~
