# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    body_converter:
        enabled: true
        validate: true
        validation_errors_argument: violations
    param_fetcher_listener:  force
    allowed_methods_listener:  true
    routing_loader: true
    view:
        view_response_listener:  true
    serializer:
        serialize_null: true
#    exception:
#        codes:
#            App\Exception\MyException: 403
#        messages:
#            App\Exception\MyException: Forbidden area.
    format_listener:
        rules:
            - { path: ^/api(?!/doc), prefer_extension: true, fallback_format: json, priorities: [ json ] }
            - { path: ^/, stop: true }
