security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    # Managed by database, check App\Security\RoleHierarchy and App\Security\RoleHierarchyVoter
    role_hierarchy:
#        ROLE_ADMINISTRATION: [ ROLE_USERS_MANAGEMENT ]
#        ROLE_ADMIN:
#            - ROLE_USER
#            - ROLE_PRE_DECLARATION
#            - ROLE_ASSISTANCE
#            - ROLE_ALERTS
#            - ROLE_CONTENT_MANAGEMENT
#            - ROLE_ADMINISTRATION
#        ROLE_SUPER_ADMIN: [ ROLE_ADMIN ]

    providers:
        back_office_user_provider:
            id: back_office_user.provider
        api_user_provider:
            id: api_user.provider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api_public:
            pattern: ^/api/public
            security: false
        api_doc:
            pattern: ^/api/doc
            security: false
        api_login:
            pattern: ^/api/login
            stateless: true
            provider: api_user_provider
            guard:
                authenticators:
                    - username_password.authenticator
        api:
            pattern: ^/api
            stateless: true
            provider: api_user_provider
            simple_preauth:
                authenticator: jwt.authenticator
        main:
            pattern: ^/
            form_login:
                provider: back_office_user_provider
#                csrf_provider: security.csrf.token_manager # Use form.csrf_provider instead for Symfony <2.4
                success_handler: authentication.handler.login_success_handler
                check_path: /backoffice/login_check
                login_path: /backoffice/login
            logout:
                path: fos_user_security_logout
                target: /backoffice/login
            anonymous: true
#            security: false

    access_control:
        - { path: ^/api, roles: [ ROLE_MOBILE_USER ] }
        - { path: ^/backoffice/login$, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }
        - { path: ^/, roles: [ ROLE_USER ] }